### ISSUE TITLE
[Module Import Error] No module named 'muar.transforms'

### ISSUE THREAD

**Issue by Gwang-chae** [adam-mehdi/MuarAugment#1]
Hi! When I import MuAugmen, I got the following error message.
I'd like to try your great module, can you modify it?

I'm using PyTorch 1.7.1
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-20-2c47332d23cd> in <module>
      3 import muar.augmentations
      4 from muar.augmentations import BatchRandAugment
----> 5 from muar.augmentations import MuAugment

/opt/conda/lib/python3.8/site-packages/muar/augmentations/MuAugment.py in <module>
      5 import pytorch_lightning as pl
      6 
----> 7 from muar.transforms import BatchRandAugment
      8 from muar.loss import MixUpCrossEntropy
      9 

ModuleNotFoundError: No module named 'muar.transforms'

**Comment by adam-mehdi** [comment]
Thanks for the issue, and so sorry for the late reply! That's an error with the current PyPi version, but the repository has fixed that error. 

For the time being, just pip install from the repo `!pip install git+https://github.com/adam-mehdi/V2Iformer.git`. Make sure to restart your runtime afterwards. For example, here it is working:

<img width="645" alt="image" src="https://user-images.githubusercontent.com/62762546/184398577-96981969-b935-4193-8fc1-e3b28a34de55.png">
