### ISSUE TITLE
Integration within Lightning Flash

### ISSUE THREAD

**Issue by tchaton** [adam-mehdi/MuarAugment#2]
Hey @adam-mehdi,

Very cool library ! Would you like to contribute some to https://github.com/PyTorchLightning/lightning-flash ?

It would be also great to combine your notebooks into one great tutorial for image classification data augmentation: https://github.com/PyTorchLightning/lightning-tutorials

Best regards,
T.C

**Comment by adam-mehdi** [comment]
Thanks so much for the offer, and sorry for the late reply! I'm a big fan of PyTorch Lightning and Lightning Flash, so I'll look into doing that integration soon
